{% set name = "bcdp" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4fc21ab31f30a01292c15b8f342b12aae1ef9f04bb6c9e955a3e23eec2dfdb45

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - xarray >=0.13.0
    - cartopy
    - requests
    - netCDF4

test:
  imports:
    - bcdp

about:
  home: https://github.com/bcdp/bcdp
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Library for generating climate model evaluation pipelines.'
  dev_url: https://github.com/bcdp/bcdp

extra:
  recipe-maintainers:
    - agoodm
