travis:
  secure:
    BINSTAR_TOKEN: nLdwGJYwCsJK3PyZ7PcJwYnPy+rUhoVd7+Tj2S19vsi2SX15TUC8XROJxl8XSohM3P++bL7EYjaWZmh5OxJjEdgNbewFLyY9phT3tA4huuBW2CtigwkFXyF87//2O+eVb/G5BcCst+mEk1n5rWrhODS3L2RlYrYjrPKD3yiKnGmceslLvRSY6p7+RMeGe9yc1ZKbL7qgKkLRqqRJdB7p4c1X7+UTC0bCu21rYAytbdXsNfBBTM6yuEloZ17GL4PTma5kbaeEdyZ1Fy17u4trqdzvF4b3Wwo+sR3tBIVebdPL4gv36NId3Hh8cMvkiTQNenFh00Uh7aNrxDECLp4kzi8tfPsAAma6nq133wJ8BYY5U/n2yk8lui1ZZ9ge6QDMBW4mEm8ijFeO0IpdvAQyyVCMyjM1CIHQHbA4gqB1akumDgB7gdwNYGFLPYit1aizjQbpiqRMQIT/nxAiePVr50aVPfGIeyX9kWoBC/LgdZVHIwnjgEViz3AGLjwBp8fwyG4nMobSLJ/liIyZRJdcEQEHtxLPYpesVBsyQHtmEQpa+5xtoTN+LKnxBjVlxhC0MMrDaYmP9MXwCAoTaI9Cdh/OHph30b41YJW/CQPG7nZD5fjNUfwEwoZKaosDp4cdeXgDfhFwln82ZahKZG6HDPoKYY43uKxkGCXP0v4xcmo=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
